version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: reborn-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "reborn_db"
      TZ: "Asia/Seoul"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - reborn-network

  redis:
    image: redis:7.0-alpine
    container_name: reborn-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - reborn-network

  mongodb:
    image: mongo:6.0
    container_name: reborn-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
    volumes:
      - ./mongo_data:/data/db
    networks:
      - reborn-network

  backend-app:
    image: seongh06/reborn-backend:latest
    container_name: kopring-backend-server
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/reborn_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_MONGODB_URI=mongodb://root:${MONGO_ROOT_PASSWORD}@mongodb:27017/reborn_db?authSource=admin
      - TZ=Asia/Seoul
    depends_on:
      - database
      - redis
      - mongodb
    networks:
      - reborn-network

networks:
  reborn-network:
    driver: bridge