version: '3.8'

services:
  database:
    image: mysql:8.0
    container_name: reborn-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "reborn"
      TZ: "Asia/Seoul"
    volumes:
      - ./mysql_reborn_data:/var/lib/mysql
    networks:
      - reborn-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0-alpine
    container_name: reborn-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - reborn-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  backend-app:
    image: seongh06/reborn-backend:latest
    container_name: reborn-backend-server
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JWT_SECRET=${JWT_SECRET}
      - DB_URL=jdbc:mysql://database:3306/reborn?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
      - DB_USERNAME=root
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SQL_INIT_MODE=never
      - JPA_DDL_AUTO=validate
      - TZ=Asia/Seoul
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - reborn-network

networks:
  reborn-network:
    driver: bridge
